### ISSUE TITLE
Automated monthly build (GitHub Actions)

### ISSUE THREAD

**Issue by dmotte** [loomchild/volume-backup#43]
First of all, thanks for creating this image! It is really useful to me

With **GitHub Actions**, you can schedule **automatic monthly builds** of your Docker image to ensure that it's always updated with the latest **Alpine** version and the latest packages. To enable that, you just need to add the following `schedule` section to your `.github/workflows/publish-image.yml` and that's all.

```yaml
on:
  push:
    branches:
      - master
  schedule:
    # Runs automatically on the 27th of every month at 05.30 UTC
    - cron:  "30 05 27 * *"
```

I already use this feature (e.g. [here](https://github.com/dmotte/desktainer-plus/blob/main/.github/workflows/docker.yml)) and it is super useful 🙂 thanks GitHub!

Let me know what you think about it and thanks again for your work :)
